### ISSUE TITLE
Error when loading generated library with manufacturers part number specified

### ISSUE THREAD

**Issue by 0x544D** [xesscorp/KiPart#30]
Hi, first of all thanks for the great work :) This tool helped me a lot! I guess i found a bug, or i'm too stupid to use the tool correctly ^^.
I noticed when specifing a manufacturers part number in the first row of the csv file, kipart will generate the "F 4" field in the header of the symbol. Unfortunately it does this with a whitespace between the F and the 4, which leads to error when i try to load the library. When i delete the whitespace between the two characters manually, the library loads just fine. I have attached the cvs file and the generated lib file, so that you can see for yourself.

i used the following command on Windows 10:
kipart JM1.csv -r generic -o ../libraries/JM1_FPGA_Con_faulty.lib

Kicad Version: 4.0.7

Thanks again for your work!

[ManufacturersBug.zip](https://github.com/xesscorp/KiPart/files/1410200/ManufacturersBug.zip)

**Comment by xesscorp** [comment]
Sorry for the delay in fixing this.
