### ISSUE TITLE
NC pins not bundled despite -b parameter

### ISSUE THREAD

**Issue by gustep12** [xesscorp/KiPart#33]
I am defining a new footprint for a molex connector where several pins are either GND or NC.

The multiple GND pins are properly bundled with the -b option.

The multiple NC pins remain unbundled in the resulting KiCad component.

Test-Connector
Pin,Name,Type,Side
1,GND,pwr,right
2,GND,pwr,right
3,DAC.1_out,out,right
4,DAC.2_out,out,right
5,DAC.1_10%,out,right
6,DAC.2_10%,out,right
7,NC,nc,right
8,NC,nc,right
9,NC,nc,right
10,NC,nc,right

**Comment by gustep12** [comment]
Ok, I just read that's a feature in the newest revision, not a bug.

**Comment by xesscorp** [comment]
Yes, bundling NC pins was leading to ERC errors in EESchema.
