### ISSUE TITLE
Feature Request: Connector output format (maybe more)

### ISSUE THREAD

**Issue by ANWatson** [xesscorp/KiPart#35]
Great tool, but an excellent feature would be to add a connector output format for Eg DIP headers similar to that implemented on the rohrbacher web tool - see attached pic.

I'm breadboarding an STM32 project from the LQFP144 package on an adapter board and this would be SUPER useful for labeling the pins on the breakout connectors.
ie create 4 36 pin connectors in the "CONN1" style in the picture
![capture](https://user-images.githubusercontent.com/36407279/37528048-816d0870-292b-11e8-969a-be910bdff172.PNG)

Maybe I can have a crack at it over the weekend

**Comment by xesscorp** [comment]
This is easy enough to do. List your pins in order in the "Pin" column: 1,2,3,4,5,... Then in the "Side" column, just alternate: left, right, left, right, left, ...
