### ISSUE TITLE
Footprint and datasheet fields seem to be required in kicad 5

### ISSUE THREAD

**Issue by manitou3** [xesscorp/KiPart#39]
It seems that with Kicad 5, that the F2 and F3 fields are required (i.e. footprint and datasheet). I couldn't find any official documentation to back this up other than kicad won't load the symbol library created with kipart unless those fields are in the file. There is documentation I found here:
https://forum.kicad.info/t/lib-format-description/3226
that seems to indicate that F2 and F3 were  required back in 2016, but perhaps not enforced?

**Comment by xesscorp** [comment]
I added the F2 and F3 fields to KiPart along with the capability of setting them in the CSV file.
