### ISSUE TITLE
How to use this?

### ISSUE THREAD

**Issue by eabase** [xesscorp/KiPart#41]
How do you actually use this tool? 
Please add some info to the Wiki or README. 
Cheers!

**Comment by xesscorp** [comment]
Near the top of the README is a link labeled "Documentation".

**Comment by eabase** [comment]
@xesscorp 

Yes, sorry, perhaps I could have been more clear. 
The text in the link doesn't show how to actually use this for creating and importing **one** component.  It look great to create it on command line, from a CSV, but then ho do you include that *one* component in a library you already have? (Without risking to overwrite it?)

**Comment by xesscorp** [comment]
-a, --append, --add option. It's in the documentation and also in the output generated using the --help option.
