### ISSUE TITLE
Issue with multiple units symbol

### ISSUE THREAD

**Issue by ngocminhdao88** [xesscorp/KiPart#48]
I cannot create multiple units symbol, when the manufacture's number or symbol's description field is populated.

I am using KiPart  0.1.42

CSV file i used with KiPart:
[sample_csv.zip](https://github.com/xesscorp/KiPart/files/4677242/sample_csv.zip)

Content of working and non-working lib file:
## non-working
![nonworking_symbol](https://user-images.githubusercontent.com/16566961/82814983-8150df80-9e98-11ea-8e16-a49b203ddfd9.png)
## working
![working_symbol](https://user-images.githubusercontent.com/16566961/82814985-81e97600-9e98-11ea-9097-29d1acb4e2b8.png)

**Comment by xesscorp** [comment]
I found an error and fixed it. Please install the modified program:

```
pip install -U git+https://github.com/xesscorp/KiPart
```
If the error is fixed, please close this issue. Then I will upload the modified program to Pypi.
