### ISSUE TITLE
Flag for changing the generated files to follow the look of the KiCAD library

### ISSUE THREAD

**Issue by korken89** [xesscorp/KiPart#53]
**Is your feature request related to a problem? Please describe.**
Not a problem, but inconsistency. 
The generated ports using KiPart has a line width of ~0.3 and no fill, while the KiCAD packaged library sets the width to 0 and fills the port with the background color.

**Describe the solution you'd like**
A flag for telling KiPart that the generated symbols should follow the KiCAD standard.

Not a big thing, but would be nice :)
Thanks for a great tool!

**Comment by xesscorp** [comment]
I added an option to set the line thickness of the schematic symbol box. The default settings for KiPart are now to use the background fill and a line thickness of zero.

I also added a `push` option to change the positions of the pins on each side of the schematic symbol box. A value of 0.0 pushes them to the upper-most or left-most position on the left/right or top/bottom sides. A value of 1.0 pushes them to the bottom-most or right-most position on the left-right or top-bottom sides. A value of 0.5 (the default) centers them.
