### ISSUE TITLE
Symbol layout bug when more pins right than left

### ISSUE THREAD

**Issue by thomashenauer** [xesscorp/KiPart#6]
If more pins are on the right side than on the left, the top edge of the symbol outline will be at the same height as the last pin. The usual spacing from the top most pin to the outline is therefor not present and the labeling overlaps. See attached picture.
EDIT: Only true if no pins at all on the left side.

![kipart symbol layout bug](https://cloud.githubusercontent.com/assets/6587333/12265057/2f5d097a-b93b-11e5-8c9b-76efb3ae5230.png)

**Comment by xesscorp** [comment]
Thanks for the clear error report! Problem is fixed. Update to version 0.1.14.
