### ISSUE TITLE
Wishlist: Non-boxy parts

### ISSUE THREAD

**Issue by iromero91** [xesscorp/KiPart#8]
I haven't looked at the deep parts of the code, but I was wondering if it would be possible to define "templates" for non-boxy symbols like transistors (with an arbitrary number of units and joined pins) or operational amplifiers (again with an arbitrary number of units and pinout)

**Comment by xesscorp** [comment]
It's possible but not on my to-do list since non-boxy symbols are usually associated with low pin-count parts that are easy to create (like opamps). But KiPart is FOSS, so anyone else is free to give this a try!
